# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'pack'
    packagesToPack: "Source/LazyProperty/LazyProperty/LazyProperty.csproj"
    arguments: '--configuration $(BuildConfiguration)'
    packDirectory: '$(System.DefaultWorkingDirectory)/dist'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'pack'
    packagesToPack: "Source/LazyProperty/LazyProperty.Reactive/LazyProperty.Reactive.csproj"
    arguments: '--configuration $(BuildConfiguration)'
    packDirectory: '$(System.DefaultWorkingDirectory)/dist'
  
- publish: dist
  artifact: nupkg
  displayName: 'Publish artifacts'

