# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'Tests/LazyProperty.Tests/LazyProperty.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    workingDirectory: 'Source/LazyProperty'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    workingDirectory: 'Source/LazyProperty'
